<?php

/**
 * BaseUnitMeasure
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Product
 * 
 * @method string              getName()    Returns the current record's "name" value
 * @method Doctrine_Collection getProduct() Returns the current record's "Product" collection
 * @method UnitMeasure         setName()    Sets the current record's "name" value
 * @method UnitMeasure         setProduct() Sets the current record's "Product" collection
 * 
 * @package    eMrp
 * @subpackage model
 * @author     Scoppia
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUnitMeasure extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('unit_measure');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Product', array(
             'local' => 'id',
             'foreign' => 'unit_measure_id'));
    }
}