<?php

/**
 * BaseState
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $ProductionOrder
 * 
 * @method string              getName()            Returns the current record's "name" value
 * @method Doctrine_Collection getProductionOrder() Returns the current record's "ProductionOrder" collection
 * @method State               setName()            Sets the current record's "name" value
 * @method State               setProductionOrder() Sets the current record's "ProductionOrder" collection
 * 
 * @package    eMrp
 * @subpackage model
 * @author     Scoppia
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseState extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('state');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProductionOrder', array(
             'local' => 'id',
             'foreign' => 'state_id'));
    }
}