<?php

/**
 * BaseArea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $area_id
 * @property string $codigo
 * @property string $name
 * @property Doctrine_Collection $ProductionLine
 * 
 * @method integer             getAreaId()         Returns the current record's "area_id" value
 * @method string              getCodigo()         Returns the current record's "codigo" value
 * @method string              getName()           Returns the current record's "name" value
 * @method Doctrine_Collection getProductionLine() Returns the current record's "ProductionLine" collection
 * @method Area                setAreaId()         Sets the current record's "area_id" value
 * @method Area                setCodigo()         Sets the current record's "codigo" value
 * @method Area                setName()           Sets the current record's "name" value
 * @method Area                setProductionLine() Sets the current record's "ProductionLine" collection
 * 
 * @package    eMrp
 * @subpackage model
 * @author     Scoppia
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('area');
        $this->hasColumn('area_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('codigo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProductionLine', array(
             'local' => 'id',
             'foreign' => 'area_id'));
    }
}