<?php

/**
 * BaseProductionItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $production_order_id
 * @property integer $quantity
 * @property integer $produced
 * @property integer $lost
 * @property ProductionOrder $ProductionOrder
 * 
 * @method integer         getProductionOrderId()   Returns the current record's "production_order_id" value
 * @method integer         getQuantity()            Returns the current record's "quantity" value
 * @method integer         getProduced()            Returns the current record's "produced" value
 * @method integer         getLost()                Returns the current record's "lost" value
 * @method ProductionOrder getProductionOrder()     Returns the current record's "ProductionOrder" value
 * @method ProductionItem  setProductionOrderId()   Sets the current record's "production_order_id" value
 * @method ProductionItem  setQuantity()            Sets the current record's "quantity" value
 * @method ProductionItem  setProduced()            Sets the current record's "produced" value
 * @method ProductionItem  setLost()                Sets the current record's "lost" value
 * @method ProductionItem  setProductionOrder()     Sets the current record's "ProductionOrder" value
 * 
 * @package    eMrp
 * @subpackage model
 * @author     Scoppia
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductionItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('production_item');
        $this->hasColumn('production_order_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('quantity', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('produced', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('lost', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ProductionOrder', array(
             'local' => 'production_order_id',
             'foreign' => 'id'));
    }
}