<?php

/**
 * BaseProductLineProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $product_id
 * @property integer $production_line_id
 * @property integer $operational_rate
 * @property ProductionLine $ProductionLine
 * @property Product $Product
 * 
 * @method integer            getProductId()          Returns the current record's "product_id" value
 * @method integer            getProductionLineId()   Returns the current record's "production_line_id" value
 * @method integer            getOperationalRate()    Returns the current record's "operational_rate" value
 * @method ProductionLine     getProductionLine()     Returns the current record's "ProductionLine" value
 * @method Product            getProduct()            Returns the current record's "Product" value
 * @method ProductLineProduct setProductId()          Sets the current record's "product_id" value
 * @method ProductLineProduct setProductionLineId()   Sets the current record's "production_line_id" value
 * @method ProductLineProduct setOperationalRate()    Sets the current record's "operational_rate" value
 * @method ProductLineProduct setProductionLine()     Sets the current record's "ProductionLine" value
 * @method ProductLineProduct setProduct()            Sets the current record's "Product" value
 * 
 * @package    eMrp
 * @subpackage model
 * @author     Scoppia
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductLineProduct extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_line_product');
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('production_line_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('operational_rate', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ProductionLine', array(
             'local' => 'production_line_id',
             'foreign' => 'id'));

        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id'));
    }
}