<?php

/**
 * BaseProductionLine
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $company_id
 * @property integer $area_id
 * @property string $codigo
 * @property string $name
 * @property string $model
 * @property Company $Company
 * @property Area $Area
 * @property Doctrine_Collection $ProductLineProduct
 * @property Doctrine_Collection $ProductionOrder
 * 
 * @method integer             getCompanyId()          Returns the current record's "company_id" value
 * @method integer             getAreaId()             Returns the current record's "area_id" value
 * @method string              getCodigo()             Returns the current record's "codigo" value
 * @method string              getName()               Returns the current record's "name" value
 * @method string              getModel()              Returns the current record's "model" value
 * @method Company             getCompany()            Returns the current record's "Company" value
 * @method Area                getArea()               Returns the current record's "Area" value
 * @method Doctrine_Collection getProductLineProduct() Returns the current record's "ProductLineProduct" collection
 * @method Doctrine_Collection getProductionOrder()    Returns the current record's "ProductionOrder" collection
 * @method ProductionLine      setCompanyId()          Sets the current record's "company_id" value
 * @method ProductionLine      setAreaId()             Sets the current record's "area_id" value
 * @method ProductionLine      setCodigo()             Sets the current record's "codigo" value
 * @method ProductionLine      setName()               Sets the current record's "name" value
 * @method ProductionLine      setModel()              Sets the current record's "model" value
 * @method ProductionLine      setCompany()            Sets the current record's "Company" value
 * @method ProductionLine      setArea()               Sets the current record's "Area" value
 * @method ProductionLine      setProductLineProduct() Sets the current record's "ProductLineProduct" collection
 * @method ProductionLine      setProductionOrder()    Sets the current record's "ProductionOrder" collection
 * 
 * @package    eMrp
 * @subpackage model
 * @author     Scoppia
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductionLine extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('production_line');
        $this->hasColumn('company_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('area_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('codigo', 'string', 25, array(
             'type' => 'string',
             'length' => '25',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('model', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Company', array(
             'local' => 'company_id',
             'foreign' => 'id'));

        $this->hasOne('Area', array(
             'local' => 'area_id',
             'foreign' => 'id'));

        $this->hasMany('ProductLineProduct', array(
             'local' => 'id',
             'foreign' => 'product_id',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasMany('ProductionOrder', array(
             'local' => 'id',
             'foreign' => 'production_line_id'));
    }
}