<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/16 20:53:17
sfConfig::add(array(
  'app_is_secure' => true,
  'app_sf_guard_plugin_routes_register' => true,
  'app_sf_guard_plugin_success_signout_url' => 'homepage',
  'app_sf_guard_plugin_success_signin_url' => 'homepage',
));
