<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/16 21:36:17
sfConfig::add(array(
  'mod_productlineproduct_enabled' => true,
  'mod_productlineproduct_view_class' => 'sfPHP',
));
