<?php
// auto-generated by sfViewConfigHandler
// date: 2011/11/16 21:36:17
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'mainLayout' ? false : 'mainLayout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('mainLayout.css', '', array ());
  $response->addStylesheet('../dataTablesPlugin/css/demo_table_jui.css', '', array ());
  $response->addStylesheet('../dataTablesPlugin/themes/smoothness/jquery-ui-1.8.4.custom.css', '', array ());
  $response->addJavascript('jquery-1.4.4.min.js', '', array ());
  $response->addJavascript('../dataTablesPlugin/js/jquery.dataTables.js', '', array ());


