<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/16 21:36:09
sfConfig::add(array(
  'mod_productionline_enabled' => true,
  'mod_productionline_view_class' => 'sfPHP',
));
