<?php

/**
 * OperatorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OperatorTable extends sfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OperatorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Operator');
    }
}