<?php

/**
 * ProductionLineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductionLineTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductionLineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductionLine');
    }
}