<?php

/**
 * ProductFamilyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductFamilyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductFamilyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductFamily');
    }
}