<?php

/**
 * ProductionLine
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    eMrp
 * @subpackage model
 * @author     Scoppia
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProductionLine extends BaseProductionLine
{

}