<?php

/**
 * ProductLineProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductLineProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductLineProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductLineProduct');
    }
}