<?php

/**
 * ProductionItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductionItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductionItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductionItem');
    }
}