<?php

/**
 * UnitMeasureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UnitMeasureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UnitMeasureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UnitMeasure');
    }
}