<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/04/07 18:54:38

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=eMrp',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
