<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/04/07 18:54:38
sfConfig::add(array(
  'app_is_secure' => true,
  'app_sf_guard_plugin_routes_register' => true,
  'app_sf_guard_plugin_success_signout_url' => 'homepage',
  'app_sf_guard_plugin_success_signin_url' => 'homepage',
));
