<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/16 20:54:44
sfConfig::add(array(
  'mod_productionitem_enabled' => true,
  'mod_productionitem_view_class' => 'sfPHP',
));
