<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/16 20:58:51
sfConfig::add(array(
  'mod_productlineproduct_enabled' => true,
  'mod_productlineproduct_view_class' => 'sfPHP',
));
