<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/16 20:52:42
sfConfig::add(array(
  'mod_productionorder_enabled' => true,
  'mod_productionorder_view_class' => 'sfPHP',
));
